name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: 🥜 Check out project
      uses: actions/checkout@v2
    - name: ⬆️ Fetch latest software lists
      run: |
        sudo apt update -q

    - name: 🟥 Setup Redis
      run: |
        sudo apt install redis-server -q

    - name: ⚙️ Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1
          6.x
          7.x

    - name: 🟢 Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: 🏗️ Build and test everything EXCEPT TempDb 🧪
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        SUPPRESS_DOWNLOAD_PROGRESS: 1
      run: |
        npm ci
        npm run test-not-tempdb

    - name: 🏗️ Build and test TempDb 🧪
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        SUPPRESS_DOWNLOAD_PROGRESS: 1
      run: |
        npm ci
        npm run test-tempdb

    - name: 📃 Upload build report
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: buildreports/
